# MinerTrack Mod Metadata for Forge
# This file declares the mod to the Forge mod loader.
# It lives at META-INF/mods.toml inside the JAR.

modLoader = "javafml"
loaderVersion = "[1,)" # Compatible with NeoForge 1.20

license = "MIT"

[[mods]]
modId = "minertrack"
version = "2.1.0.0"
displayName = "MinerTrack"
# logoFile is optional — omit for now
description = '''
The Advanced Anti-Xray that you need.
Have you ever dreamed of a powerful anti-xray?
'''
authors = "Author87668"

[[dependencies.minertrack]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,)"
    ordering = "NONE"
    side = "SERVER"
