#### MinerTrack Anti-Xray Configuration - config.yml ##############################
#
#   Welcome to MinerTrack anti-xray configuration file.
#   This file defines global settings specifically optimized for anti-xray detection.
#
#  Useful Links:
#  Discord: https://discord.gg/MzTea2W9cb
#  Github: https://github.com/At87668/MinerTrack
#  SpigotMC: https://www.spigotmc.org/resources/120562/
#  Hangar: https://hangar.papermc.io/Author87668/MinerTrack
#  Modrinth: https://modrinth.com/plugin/minertrack
#
##################################################################################

# Check for updates on startup (recommended for latest optimizations).
check_update: true

# Visual effect when a player is kicked using /minertrack kick (default: true)
kick_strike_lightning: true

# Log Violations (default: true)
# Logs all detections in /plugins/MinerTrack/logs for easier monitoring.
log_file: true

# Auto-delete outdated logs after specified days (-1 to disable auto-deletion)
delete_time: 30

# Deny Bypass Permission - force checks on all players, including Operators.
disable_bypass_permission: false

#############################################################################################################################
##        ##   This plugin in order to capture XRayer quickly, might generate false positives for players who are lucky!   ##
##  Warn  ##   Be careful not to set the VL threshold too low!                                                             ##
##        ##   Don't detect for common ores either, you should only detect for rare ores!                                  ##
#############################################################################################################################

xray:
  enable: true  # Enable X-ray detection

  # At what height should I start detecting X-Ray?
  # Worlds that are not listed do not have XRay detection.
  worlds:
    world:
      enable: true
      max-height: 64
    world_nether:
      enable: true
      max-height: 128
    world_the_end:
      enable: false
    all_unnamed_world:
      enable: false
  
  # The type of ore a player has to mine before being able to be checked
  # List of allowed materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  rare-ores:
    - ANCIENT_DEBRIS
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
  
  # Mined length record limit (Unit: block)
  max_path_length: 500
  
  # Explosion Detection (alpha)
  explosion:
    explosion_retention_time: 600  # Information is removed after {n} seconds after the mineral is exposed to the explosion
    entity-explode-check: false    # Whether or not the mining of minerals caused by explosions counts towards player mining?
    base_vl_rate: 2.0              # VL multiplier when the player's blast hit rate is suspicious
    suspicious_hit_rate: 0.1       # Suspicious when the player hits what the percentage is? (0.1 = 10%)
    
  # Path record is reset after the player VL is 0 {n} minutes.
  trace_remove: 15
  
  # Cave Detection
  cave-detection:
    # Satisfying the air-threshold will think they are in a cave.
    air-threshold: 4         # When the number of cave air blocks reaches several, the player is considered to be in a cave?
    air-detection-range: 2   # 3 = 7x7x7, 2 = 5x5x5
    cave_check_skip_vl: true # VL add of whether or not to skip cave behavior

  # Violation level decay settings (Unit: minute)
  decay:
    interval: 3         # The interval between decay tasks (in minutes)
    amount: 1           # The value of each linear falloff
    use_factor: false   # Whether to enable nonlinear attenuation
    factor: 0.9         # Nonlinear decay scale (only works when use_factor=true)

  # Commands executed at specified violation thresholds
  commands:
    3: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 3&7]'
    5: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 5&7]'
    6: 'minertrack kick %player% X-Ray'
